### PR TITLE
Replace httprouter with gin

### PR DESCRIPTION
**Pull request by dan-ash**

### CODE REVIEW

**Comment by s8sg** [comment]
Looks good. I'm thinking if we can add some integration test as a part of this MR. WDYT ?

**Comment by dan-ash** [comment]
I actually thought about it, but when I started I realized that I prefer to handle it as a dedicate task and not something that I can do on the way as there aren't any tests at the moment.
I will be happy to take it as another task, can you open an issue and describe what you think will be a good start?

**Comment by dan-ash** [comment]
@s8sg how do you think we should pass arguments to configure gin logging? at the moment I hard coded it to a file but I think we should allow some configurations

**Comment by s8sg** [comment]
@dan-ash I think we already have a flag called debug enabled, we can use the same. WDYT ?

**Comment by s8sg** [comment]
@dan-ash We already have a debug enabled flag. I think we can use it

**Comment by s8sg** [comment]
@dan-ash What is the status of this ? Can we merge 
Also please rebase the MR

**Comment by dan-ash** [comment]
Hi,
I will rebase and we can merge IMO

**Comment by dan-ash** [comment]
I thought it was, then I remembered you mentioned the debug flag as an option to control the logging, I will rebase and add it.

**Pull request merged**
